### PR TITLE
Token

### PR DESCRIPTION
**Pull request by seanwilliamcarroll**
~~Added Token and Lexer classes~~

~~Can lex and print most parts of our intended languages~~
~~Testing is light, mostly looked at equality of tokens and got my feel wet with RapidCheck, reorganized slightly~~
~~Trying to be diligent in using clang-format, using this command from project-dir find core blip -type f \( -iname \*.cpp -o -iname \*.hpp \) | xargs clang-format -i~~
~~std::source_location was introduced in C++20, so I wrote my own as best I could~~
~~Suggestions welcome and appreciated for all things!~~

### CODE REVIEW

**Comment by seanwilliamcarroll** [comment]
Added Token and Lexer classes

- Can lex and print most parts of our intended languages
- Testing is light, mostly looked at equality of tokens and got my feel wet with RapidCheck, reorganized slightly
- Trying to be diligent in using clang-format, using this command from project-dir find core blip -type f \( -iname \*.cpp -o -iname \*.hpp \) | xargs clang-format -i
- std::source_location does not have mutability, so I wrote my own as best I could
- Suggestions welcome and appreciated for all things!
- Especially have questions about the `SourceLocation::dump` and `Token::dump` methods: they feel sloppy, did you have a better idea of how to accomplish this? 

I think we may be ready to move on to the parser after this review.

**Comment by seanwilliamcarroll** [comment]
I think I addressed everything we discussed yesterday. Still not entirely sure if I should remove dump methods or not from `Token` and `TokenOf`? Let me know if further things to discuss.

**Comment by jonathon-bell** [comment]
Hi Sean,

This is looking good: Before merging, please see my branch “token-jab” with suggested changes to the core lexer. These include:

1) introduce factory functions of tokens - simplifies things a bot
2) introduce variadic function to format and and throw error message 
3) avoid initializing strings with “”
4) avoid testing strings for “”

Feel free to reformat or change as you wish, then merge into master.
j

**Comment by seanwilliamcarroll** [comment]
Ok all merged now! Let me know when you want to meet to discuss parsing

**Pull request merged**
